### ISSUE TITLE
catch cubist errors

### ISSUE THREAD

**Issue by jwgda** [pjaselin/Cubist#106]
Some Cubist errors seem to exit the entire Python wrapper without any exception.

E.g.,

```
sample code called exit with value 1
***No cases with known target values
```

Can these errors be caught as Python Exceptions?

**Comment by jwgda** [comment]
I am getting this response for attempting to change the sample parameter to a non-zero value (e.g. 0.10).

Why is zero the default "sample" parameter and what does a zero value mean?

**Comment by pjaselin** [comment]
Hi @jwgda and thanks for all your help in improving this package! I'd recommend you check out the original documentation here on Cubist: https://www.rulequest.com/cubist-unix.html#SAMPLE. Setting sample to 0.1 passes my tests so could you provide a reproducible example of this failing so I can better understand what's going on in this specific case? It looks like its on the prediction side though.

**Comment by jwgda** [comment]
Here is an example:

`import pandas as pd
from cubist import Cubist
import os,sys

X = pd.DataFrame([0.803949,0.792776,0.698957,0.889468,0.898589,0.780680,0.763039,0.733734,0.880098,0.749216,0.772409,0.397889,0.569687,0.863047,0.901520,0.903672,0.850031,0.967257,0.924921],columns=['X'])
y = [9.101007550426122, 10.105041400955075, 9.665428777858954, 11.108833294273804, 10.543686195210283, 10.041306334130462, 10.29213332885503, 10.229124133661102, 10.793787318304165, 9.726502315371054, 10.102863786063018, 7.843001261439629, 9.474707491805574, 10.290439628383432, 11.106171764961289, 11.73360218758805, 11.607825754410422, 11.168213131314303, 11.230738412087772]
predict = pd.DataFrame([0.795757],columns=['X'])

tree = Cubist(n_committees=5, n_rules=500, neighbors=None, unbiased=False, composite=False, extrapolation=0.05, sample=0.1, cv=None, target_label="outcome", random_state=1, verbose=0)
tree.fit(X, y)
tree.predict(predict)
`

Also, I can capture the "*** No cases with known target values" message from sys.stdout, but I'm not sure what buffer the 'sample code called exit with value 1' message is written to.

**Comment by pjaselin** [comment]
Thanks @jwgda so if you look at the verbose output, you'll see that all the rules return a constant value. Because you have sample=0.1, it's taking 10% of the data (2 rows) and building a model on that, which doesn't work in predictions. This is part of Quinlan's design for being able to take samples of very large datasets. I can raise Python exceptions but I should also probably add a warning if you're using very few samples as in this case.

**Comment by jwgda** [comment]
Thanks for the reply.  That makes sense.  And I agree that Python exceptions would be easier to manage.

My question is what does sample=0.0 mean vs. sample=1.0?  Do they both mean that all the cases are used for model building?  Why does sample=1.0 fail in above example, whereas 0.0 doesn't?  Does 0.0 simply mean that the 'sample' switch is not set (if so, should it be 'None'?)

Thanks so much for your help.

**Comment by pjaselin** [comment]
Based on the R code, it looks like I need to prevent sample=1.0 since it always produces an error, so the range is from 0.0 to 0.99.... It would probably mean using all the data to construct the model and testing on no cases, but that would be the same as saying sample=0.0. Basically a case that I need to remove.

**Comment by jwgda** [comment]
OK, thanks.  Does that mean that a 0.0 value means all the cases are used to create the model rather than a subset (i.e., the -s switch option is not used)?  This would make sense given that it runs successfully without a Cubist error, though a little counterintuitive.  Maybe a None value would make more sense?

**Comment by pjaselin** [comment]
That's my understanding based on the documentation and the model output. How does this look?: https://github.com/pjaselin/Cubist/pull/107/files
Note that because the C code doesn't accept a value of None, I have to copy the value to a new private variable and set it to 0 if sample is None. I agree this does make more sense.

**Comment by pjaselin** [comment]
I'm just not sure what would be a robust way to handling sampling with too small of a dataset. I think I might just leave that in the docs and make folks aware of it.
